
CREATE TABLE USER_INFO (
	USER_PK INT NOT NULL AUTO_INCREMENT,
	USER_NAME VARCHAR(255) NOT NULL,
	PASSWORD VARCHAR(255) NOT NULL,
	BLOCKED BIT DEFAULT 0,
	LOGIN_ATTEMPTS SMALLINT DEFAULT 0,
	FIRST_NAME VARCHAR(50) NOT NULL,
	LAST_NAME VARCHAR(50) NOT NULL,
	DATE_OF_BIRTH DATE,
	PERSON_ID VARCHAR(25),
	EMAIL VARCHAR(50),
	PRIMARY KEY (USER_PK),
	UNIQUE (USER_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


insert into user_info (user_name, password, first_name, last_name, date_of_birth, person_ID, email)
values ('user1', '123', 'Victoria', 'Chernishenko', '1996-01-23', '010203-11032', 'name1@email.com');


CREATE TABLE ROLE (
	ROLE_PK INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (ROLE_PK),
	ROLE_NAME VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE USER_INFO_ROLE (
	USER_INFO_ROLE_PK INT NOT NULL AUTO_INCREMENT,
	USER_INFO_FK INT,
	ROLE_FK INT,
	PRIMARY KEY (USER_INFO_ROLE_PK),
	CONSTRAINT ROLE_USER_INFO_FK FOREIGN KEY (USER_INFO_FK) REFERENCES USER_INFO(USER_PK) ON DELETE CASCADE,
	CONSTRAINT ROLE_USER_INFO_ROLE_FK FOREIGN KEY (ROLE_FK) REFERENCES ROLE(ROLE_PK) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE MANUFACTURER (
	MANUFACTURER_PK INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (MANUFACTURER_PK),
	MANUFACTURER_NAME VARCHAR(50)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE MODEL (
	MODEL_PK INT NOT NULL AUTO_INCREMENT,
	MANUFACTURER_FK INT,
	MODEL_NAME VARCHAR(255),
	PRIMARY KEY (MODEL_PK),
	CONSTRAINT MODEL_MANUFACTURER_FK FOREIGN KEY (MANUFACTURER_FK) REFERENCES MANUFACTURER(MANUFACTURER_PK) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE VEHICLETYPE (
	VEHICLETYPE_PK INT NOT NULL AUTO_INCREMENT,
	VEHICLETYPE_NAME VARCHAR(255),
	PRIMARY KEY (VEHICLETYPE_PK)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE TRANSMISSION (
	TRANSMISSION_PK INT NOT NULL AUTO_INCREMENT,
	TRANSMISSION_NAME VARCHAR(255),
	PRIMARY KEY (TRANSMISSION_PK)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE COLOR (
	COLOR_PK INT NOT NULL AUTO_INCREMENT,
	COLOR_NAME VARCHAR(255),
	PRIMARY KEY (COLOR_PK)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE RENTAL_STATUS (
	STATUS_PK INT NOT NULL AUTO_INCREMENT,
	STATUS_NAME VARCHAR(255),
	PRIMARY KEY (STATUS_PK)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE LOCATION (
	LOCATION_PK INT NOT NULL AUTO_INCREMENT,
	LOCATION_NAME VARCHAR(255),
	PRIMARY KEY (LOCATION_PK)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE CAR (
     CAR_PK INT NOT NULL AUTO_INCREMENT,
	 REGISTRATION_NUMBER VARCHAR(10) NOT NULL,
     MODEL_FK INT NOT NULL,
	 YEAR SMALLINT,
	 VEHICLETYPE_FK INT,
	 TRANSMISSION_FK INT,
	 COLOR VARCHAR(25),
	 PRICE INT(9),
	 PHOTO LONGBLOB,
	 AVAILABLE BIT DEFAULT 0,
     PRIMARY KEY (CAR_PK),
	 UNIQUE (REGISTRATION_NUMBER),
	 CONSTRAINT CAR_MODEL_FK FOREIGN KEY (MODEL_FK) REFERENCES MODEL(MODEL_PK) ON DELETE CASCADE,
	 CONSTRAINT CAR_VEHICLETYPE_FK FOREIGN KEY (VEHICLETYPE_FK) REFERENCES VEHICLETYPE(VEHICLETYPE_PK) ON DELETE CASCADE,
	 CONSTRAINT CAR_TRANSMISSION_FK FOREIGN KEY (TRANSMISSION_FK) REFERENCES TRANSMISSION(TRANSMISSION_PK) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE RENTAL (
	RENTAL_PK INT NOT NULL AUTO_INCREMENT,
	RENTAIL_ID VARCHAR(255),
	CAR_FK INT,
	USER_FK INT,
	PICKUP_TIME DATETIME,
	DROPOFF_TIME DATETIME,
	TOTAL_PRICE INT,
	STATUS_FK INT,
	PRIMARY KEY (RENTAL_PK),
	CONSTRAINT RENTAL_CAR_FK FOREIGN KEY (CAR_FK) REFERENCES CAR(CAR_PK) ON DELETE CASCADE,
	CONSTRAINT RENTAL_USER_FK FOREIGN KEY (USER_FK) REFERENCES USER_INFO(USER_PK) ON DELETE CASCADE,
	CONSTRAINT RENTAL_STATUS_FK FOREIGN KEY (STATUS_FK) REFERENCES RENTAL_STATUS(STATUS_PK) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
